name        : freeglut
version     : 2.8.1
release     : 9
source      :
    - http://downloads.sourceforge.net/freeglut/freeglut-2.8.1.tar.gz : dde46626a62a1cd9cf48a11951cdd592e7067c345cffe193a149dfd47aef999a
homepage    : http://freeglut.sourceforge.net/
license     :
    - MIT
summary     : OpenSource GLUT library
builddeps   :
    - pkgconfig(gl)
    - pkgconfig32(gl)
    - pkgconfig(glu)
    - pkgconfig32(glu)
    - pkgconfig32(xshmfence)
    - pkgconfig(xi)
    - pkgconfig32(xi)
    - glibc-32bit-devel
    - libgcc-32bit
    - libstdc++-32bit
emul32      : yes
description : |
    Freeglut is intended to be a 100% compatible, completely opensourced clone of the GLUT library. GLUT is a window system independent toolkit for writing OpenGL programs, implementing a simple windowing API, which makes learning about and exploring OpenGL programming very easy.
setup      : |
    %configure --prefix=/usr --disable-static
build      : |
    %make
install    : |
    %make_install
