name       : freeglut
version    : 3.0.0
release    : 10
source     :
    - https://vorboss.dl.sourceforge.net/project/freeglut/freeglut/3.0.0/freeglut-3.0.0.tar.gz : 2a43be8515b01ea82bcfa17d29ae0d40bd128342f0930cd1f375f1ff999f76a2
homepage   : http://freeglut.sourceforge.net/
license    : MIT
component  : desktop.library
emul32     : yes
summary    : OpenSource GLUT library
description: |
    Freeglut is intended to be a 100% compatible, completely opensourced clone of the GLUT library. GLUT is a window system independent toolkit for writing OpenGL programs, implementing a simple windowing API, which makes learning about and exploring OpenGL programming very easy.
builddeps  :
    - pkgconfig32(gl)
    - pkgconfig32(glu)
    - pkgconfig32(x11)
    - pkgconfig32(xext)
    - pkgconfig32(xi)
    - pkgconfig32(xxf86vm)
setup      : |
    %cmake . -DFREEGLUT_BUILD_STATIC_LIBS=OFF \
        -DCMAKE_INSTALL_LIBDIR=%libdir%
build      : |
    %make
install    : |
    %make_install
