name       : freeglut
version    : 3.2.1
release    : 12
source     :
    - https://github.com/dcnieho/FreeGLUT/archive/FG_3_2_1.tar.gz : 23b93b77ac01bc70af0c56fa3316f25ea8f136603f93df319ca74867e15134d3
homepage   : http://freeglut.sourceforge.net/
license    : MIT
component  : desktop.library
emul32     : yes
summary    : OpenSource GLUT library
description: |
    Freeglut is intended to be a 100% compatible, completely opensourced clone of the GLUT library. GLUT is a window system independent toolkit for writing OpenGL programs, implementing a simple windowing API, which makes learning about and exploring OpenGL programming very easy.
builddeps  :
    - pkgconfig32(gl)
    - pkgconfig32(glu)
    - pkgconfig32(x11)
    - pkgconfig32(xext)
    - pkgconfig32(xi)
    - pkgconfig32(xxf86vm)
setup      : |
    %cmake . -DFREEGLUT_BUILD_STATIC_LIBS=OFF \
        -DCMAKE_INSTALL_LIBDIR=%libdir%
build      : |
    %make
install    : |
    %make_install
