name       : freeglut
version    : 3.0.0
release    : 11
source     :
    - https://github.com/dcnieho/FreeGLUT/archive/FG_3_0_0.tar.gz : b0abf188cfbb572b9f9ef5c6adbeba8eedbd9a717897908ee9840018ab0b8eee
homepage   : http://freeglut.sourceforge.net/
license    : MIT
component  : desktop.library
emul32     : yes
summary    : OpenSource GLUT library
description: |
    Freeglut is intended to be a 100% compatible, completely opensourced clone of the GLUT library. GLUT is a window system independent toolkit for writing OpenGL programs, implementing a simple windowing API, which makes learning about and exploring OpenGL programming very easy.
builddeps  :
    - pkgconfig32(gl)
    - pkgconfig32(glu)
    - pkgconfig32(x11)
    - pkgconfig32(xext)
    - pkgconfig32(xi)
    - pkgconfig32(xxf86vm)
setup      : |
    %cmake . -DFREEGLUT_BUILD_STATIC_LIBS=OFF \
        -DCMAKE_INSTALL_LIBDIR=%libdir%
build      : |
    %make
install    : |
    %make_install
